Attempt to fix an [error](https://github.com/google/guava/actions/runs/5788896196/job/15689397851) in deploying snapshots:
```
[INFO] --- maven-source-plugin:3.3.0:jar (attach-sources) @ guava ---
[INFO] Building jar: /home/runner/work/guava/guava/guava/target/guava-HEAD-jre-SNAPSHOT-sources.jar
Error:  We have duplicated artifacts attached.
...
Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.3.0:jar (attach-sources) on project guava: Presumably you have configured maven-source-plugn to execute twice times in your build. You have to configure a classifier for at least on of them. -> [Help 1]
```

The error started with cl/554548816, evidently because of the upgrade to `maven-source-plugin`.

Stack Overflow suggests [a change to `jar-no-fork`](https://stackoverflow.com/a/76379125/28465), but I didn't have immediate luck with changing the deploy script, the `pom.xml`, or both to use that. (I also tried some other `pom.xml` changes to more closely match [the `maven-source-plugin` example usages](https://maven.apache.org/plugins/maven-source-plugin/usage.html), but I didn't have immediate luck there, either.)

So I'm trying just assuming that `deploy` will build the source jar for us. Certainly I'm seeing it built and installed to the _local_ repository when I run `install` and when I run `deploy -Dmaven.deploy.skip=true`, even without passing `source:jar`. So my guess is that the argument it's unnecessary. Granted, installing to the local repository is different from deploying to Maven Central. (I'm unclear on whether a similar argument, `javadoc:jar`, is necessary. I _don't_ see it installed—whether I pass `javadoc:jar` or not.)

So let's try this. I can watch https://oss.sonatype.org/content/repositories/snapshots/com/google/guava/guava/HEAD-jre-SNAPSHOT/ to see which files the next snapshot contains.

RELNOTES=n/a
PiperOrigin-RevId: 559489724